config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post "/distances/get_distance", to: "distances#get_distance", as: 'get_distance' 
  
  post "/distances/get_co2/car", to: "co2#get_co2_car", as: 'get_co2_car' 

  post "/distances/get_co2/metro", to: "co2#get_co2_metro", as: 'get_co2_metro' 

  post "/distances/get_co2/bus", to: "co2#get_co2_bus", as: 'get_co2_bus' 

  post "/distances/get_co2/intercites", to: "co2#get_co2_intercites", as: 'get_co2_intercites' 

  post "/distances/get_co2/plane", to: "co2#get_co2_plane", as: 'get_co2_plane' 

  post "/distances/get_co2/rer", to: "co2#get_co2_rer", as: 'get_co2_rer' 

  post "/distances/get_co2/train", to: "co2#get_co2_train", as: 'get_co2_train' 

  post "/distances/get_co2/moto", to: "co2#get_co2_moto", as: 'get_co2_moto' 
  
  root "distances#index" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/co2.rb
class CO2 < ApplicationRecord
end

app/models/distance.rb
class Distance < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/co2_controller.rb
require "httparty"

class Co2Controller < ApplicationController
  include HTTParty
  base_uri 'api.monimpacttransport.fr/beta'

  def get_co2
    @distance = params[:distance]
    @options = { query: { km: @distance, filter: 'all', fields: 'emoji' }, format: :plain }
    @co2 = self.class.get('/getEmissionsPerDistance', @options).parsed_response
    @co2 = JSON.parse @co2, symbolize_names: true
  end

  def get_co2_car
    @co2 = get_co2
    @name = 'Voiture (thermique)'
    @emoji = @co2.select { |k, v| k[:name] == @name }.first[:emoji][:main]
    @co2 = @co2.select { |k, v| k[:name] == @name }.first[:emissions][:kgco2e]
  end  

  def get_co2_metro
    @co2 = get_co2
    @name = 'Métro'
    @emoji = @co2.select { |k, v| k[:name] == @name }.first[:emoji][:main]
    @co2 = @co2.select { |k, v| k[:name] == @name }.first[:emissions][:kgco2e]
  end

  def get_co2_plane
    @co2 = get_co2
    @name = 'Avion'
    @emoji = @co2.select { |k, v| k[:name] == @name }.first[:emoji][:main]
    @co2 = @co2.select { |k, v| k[:name] == @name }.first[:emissions][:kgco2e]
  end

  def get_co2_moto
    @co2 = get_co2
    @name = 'Moto'
    @emoji = @co2.select { |k, v| k[:name] == @name }.first[:emoji][:main]
    @co2 = @co2.select { |k, v| k[:name] == @name }.first[:emissions][:kgco2e]
  end

  def get_co2_bus
    @co2 = get_co2
    @name = 'Bus (électrique)'
    @emoji = @co2.select { |k, v| k[:name] == @name }.first[:emoji][:main]
    @co2 = @co2.select { |k, v| k[:name] == @name }.first[:emissions][:kgco2e]
  end

  def get_co2_train
    @co2 = get_co2
    @name = 'TGV'
    @emoji = @co2.select { |k, v| k[:name] == @name }.first[:emoji][:main]
    @co2 = @co2.select { |k, v| k[:name] == @name }.first[:emissions][:kgco2e]
  end

  def get_co2_rer
    @co2 = get_co2
    @name = 'RER ou Transilien'
    @emoji = @co2.select { |k, v| k[:name] == @name }.first[:emoji][:main]
    @co2 = @co2.select { |k, v| k[:name] == @name }.first[:emissions][:kgco2e]
  end

  def get_co2_intercites
    @co2 = get_co2
    @name = 'Intercités'
    @emoji = @co2.select { |k, v| k[:name] == @name }.first[:emoji][:main]
    @co2 = @co2.select { |k, v| k[:name] == @name }.first[:emissions][:kgco2e]
  end
end

app/controllers/distances_controller.rb
class DistancesController < ApplicationController

  # GET /distances or /distances.json
  def index

  end


  def get_distance
    matrix = GoogleDistanceMatrix::Matrix.new
    matrix.configure do |config|
      config.google_api_key = Figaro.env.google_api_key
    end

    address = GoogleDistanceMatrix::Place.new address: distance_params['from_address']
    dest_address = GoogleDistanceMatrix::Place.new address: distance_params['to_address']
    
    matrix.origins << address
    matrix.destinations << dest_address


    # Get the distance between the two addresses.
    # matrix.origins = address
    # matrix.destinations = dest_address

    @distance = matrix.data.as_json.flatten
    @distance = @distance.first['distance_in_meters']
  end

  def distance_params  
    params.require(:distances).permit(:from_address, :to_address).to_h
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/distances_helper.rb
module DistancesHelper
end

app/views/co2/get_co2_bus.html.erb
<div>
<div class="result">
Voici votre consommation en CO2
</div>

<div class="title">
  Cela représente en <%= @name %> <%= @emoji %> : <%= @co2 %> kg de CO2.
</div>

<div class="title">
<%= link_to 'Calculer pour un autre itinéraire', root_path %>
</div>
</div>

app/views/co2/get_co2_car.html.erb
<div>
<div class="result">
Voici votre consommation en CO2
</div>

<div class="title">
  Cela représente en <%= @name %> <%= @emoji %> : <%= @co2 %> kg de CO2.
</div>

<div class="title">
<%= link_to 'Calculer pour un autre itinéraire', root_path %>
</div>
</div>

app/views/co2/get_co2_intercites.html.erb
<div>
<div class="result">
Voici votre consommation en CO2
</div>

<div class="title">
  Cela représente en <%= @name %> <%= @emoji %> : <%= @co2 %> kg de CO2.
</div>

<div class="title">
<%= link_to 'Calculer pour un autre itinéraire', root_path %>
</div>
</div>

app/views/co2/get_co2_metro.html.erb
<div>
<div class="result">
Voici votre consommation en CO2
</div>

<div class="title">
  Cela représente en <%= @name %> <%= @emoji %> : <%= @co2 %> kg de CO2.
</div>

<div class="title">
<%= link_to 'Calculer pour un autre itinéraire', root_path %>
</div>
</div>

app/views/co2/get_co2_moto.html.erb
<div>
<div class="result">
Voici votre consommation en CO2
</div>

<div class="title">
  Cela représente en <%= @name %> <%= @emoji %> : <%= @co2 %> kg de CO2.
</div>

<div class="title">
<%= link_to 'Calculer pour un autre itinéraire', root_path %>
</div>
</div>

app/views/co2/get_co2_plane.html.erb
<div>
<div class="result">
Voici votre consommation en CO2
</div>

<div class="title">
  Cela représente en <%= @name %> <%= @emoji %> : <%= @co2 %> kg de CO2.
</div>

<div class="title">
<%= link_to 'Calculer pour un autre itinéraire', root_path %>
</div>
</div>

app/views/co2/get_co2_rer.html.erb
<div>
<div class="result">
Voici votre consommation en CO2
</div>

<div class="title">
  Cela représente en <%= @name %> <%= @emoji %> : <%= @co2 %> kg de CO2.
</div>

<div class="title">
<%= link_to 'Calculer pour un autre itinéraire', root_path %>
</div>
</div>

app/views/co2/get_co2_train.html.erb
<div>
<div class="result">
Voici votre consommation en CO2
</div>

<div class="title">
  Cela représente en <%= @name %> <%= @emoji %> : <%= @co2 %> kg de CO2.
</div>

<div class="title">
<%= link_to 'Calculer pour un autre itinéraire', root_path %>
</div>
</div>

app/views/distances/get_co2.html.erb
<div>
<div class="result">
Voici votre consommation en CO2
</div>

<div class="title">
Cela représente en voiture : <%= @distance %> kg de CO2.
</div>

<div class="title">
Cela représente en transport en commun un total de <%= @distance %> kg de CO2.
</div>

<div class="title">
<%= link_to 'Calculer pour un autre itinéraire', :back %>
</div>
</div>

app/views/distances/get_distance.html.erb
<div>


<% @distance = @distance.to_f / 1000 %>
  <div class="result">
    La distance est de : <%= @distance %> km.
  </div>

<% if @distance < 10 %>
<div class="title">
    Vous parcourez moins de 10 kilomètres.<br>
    Vous pouvez envisager de faire ce trajet à pied ou en vélo mécanique.<br>
    L'impact en CO2 sera donc nul.<br>
  </div>
<% end %>

<div class="title">
<%= form_with scope: "distances", url: get_co2_car_path, method: :post do |form| %>
<%= hidden_field_tag 'distance', @distance %>
  <%= form.submit "Calculer pour la consommation en voiture" %>
<% end %>
</div>

<div class="title">
<%= form_with scope: "distances", url: get_co2_moto_path, method: :post do |form| %>
<%= hidden_field_tag 'distance', @distance %>
  <%= form.submit "Calculer pour la consommation en moto" %>
<% end %>
</div>

<% if @distance < 15 %>

<div class="title">
<%= form_with scope: "distances", url: get_co2_metro_path, method: :post do |form| %>
<%= hidden_field_tag 'distance', @distance %>
  <%= form.submit "Calculer pour la consommation en métro" %>
<% end %>
</div>

<div class="title">
<%= form_with scope: "distances", url: get_co2_bus_path, method: :post do |form| %>
<%= hidden_field_tag 'distance', @distance %>
  <%= form.submit "Calculer pour la consommation en bus" %>
<% end %>
</div>

<% end %>

<% if @distance > 10 && @distance < 100 %>

<div class="title">
<%= form_with scope: "distances", url: get_co2_rer_path, method: :post do |form| %>
<%= hidden_field_tag 'distance', @distance %>
  <%= form.submit "Calculer pour la consommation en RER/Transilien" %>
<% end %>
</div>

<% end %>

<% if @distance > 30 %>

<div class="title">
<%= form_with scope: "distances", url: get_co2_intercites_path, method: :post do |form| %>
<%= hidden_field_tag 'distance', @distance %>
  <%= form.submit "Calculer pour la consommation en Intercités" %>
<% end %>
</div>

<% end %>

<% if @distance > 150 %>

<div class="title">
<%= form_with scope: "distances", url: get_co2_train_path, method: :post do |form| %>
<%= hidden_field_tag 'distance', @distance %>
  <%= form.submit "Calculer pour la consommation en train" %>
<% end %>
</div>

<% end %>

<% if @distance > 400 %>

<div class="title">
<%= form_with scope: "distances", url: get_co2_plane_path, method: :post do |form| %>
<%= hidden_field_tag 'distance', @distance %>
  <%= form.submit "Calculer pour la consommation en avion" %>
<% end %>
</div>

<% end %>


<div class="title">
<%= link_to 'Calculer pour un autre itinéraire', root_path %>
</div>
</div>

app/views/distances/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Bienvenue sur notre calculateur d'émissions de CO2, selon votre moyen de transport</h1>
<div class="center">


<div class="form">
<%= form_with scope: "distances", url: get_distance_path, method: :post do |form| %>
  <div class="title">
  Calculer la distance parcourue
  </div>

  <div class="input">
  <%= form.label :from_address, "Adresse de départ :" %>
  <%= form.text_field :from_address %>
  </div>

  <div class="input">
  <%= form.label :to_address, "Adresse d'arrivée :" %>
  <%= form.text_field :to_address %>
  </div>
  <div class="button">
  <%= form.submit "Calculer" %>
</div>
<% end %>

</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>